### ISSUE TITLE
My results do not agree with the results in the paper

### ISSUE THREAD

**Issue by Lizi271** [IDKiro/DehazeFormer#12]
用本文的代码和数据集（ITS)跑DehazeFormer-S,得到PSNR=36.54,SSIM=0.992;本论文中对应的PSNR=36.82,SSIM=0.992。请问这是什么原因呢？或者有没有小伙伴遇到类似的情况？

**Comment by IDKiro** [comment]
实验设置一样么，包括batch size、学习率等？
包的版本以及安装的方式一样么，特别是opencv，不同安装方式的jpeg编解码器不一样？

DehazeFormer-S只跑过一次训练（只有DehazeFormer-L跑了多个然后挑了个40出头的），但是训练的可重复性应该挺高的，不至于差别这么大才对。
当然，不排除实验代码和整理后的开源代码存在不同，提供的模型只有后加的DehazeFormer-W和DehazeFormer-D是用这份开源代码跑的。

**Comment by IDKiro** [comment]
请问你有跑过DehazeFormer-T和DehazeFormer-B么。因为我检查了一下，indoor的DehazeFormer-S和DehazeFormer-M是所有实验中最早跑的，之后做过一次训练代码重构，可能产生了影响。如果确实有影响的话，那就必须得对照一下训练代码的差异然后修正开源代码，论文中的数据也得更新，不过这可能要等论文返审稿意见以后了，最近实验室服务器很紧张。

**Comment by Lizi271** [comment]
T和D还没跑，我的batchsize是16，其他不变



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月16日(周四) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDKiro/DehazeFormer] 用本文的代码和数据集跑不出本论文中所说的baseline (Issue #12)




 
请问你有跑过DehazeFormer-T和DehazeFormer-B么。因为我检查了一下，indoor的DehazeFormer-S和DehazeFormer-M是所有实验中最早跑的，之后做过一次训练代码重构，可能产生了影响。如果确实有影响的话，那就必须得对照一下训练代码的差异然后修正开源代码，论文中的数据也得更新，不过这可能要等论文返审稿意见以后了，最近实验室服务器很紧张。

**Comment by IDKiro** [comment]
batch size变小的话，实验结果变低是比较正常的。
请问学习率有根据batch size改变进行更改么。

**Comment by Lizi271** [comment]
我今天打算跑一下DehazeFormer-T,结果出来，我回复您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月16日(周四) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDKiro/DehazeFormer] 用本文的代码和数据集跑不出本论文中所说的baseline (Issue #12)




 
请问你有跑过DehazeFormer-T和DehazeFormer-B么。因为我检查了一下，indoor的DehazeFormer-S和DehazeFormer-M是所有实验中最早跑的，之后做过一次训练代码重构，可能产生了影响。如果确实有影响的话，那就必须得对照一下训练代码的差异然后修正开源代码，论文中的数据也得更新，不过这可能要等论文返审稿意见以后了，最近实验室服务器很紧张。

**Comment by Lizi271** [comment]
没有，学习率保持不变



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月16日(周四) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDKiro/DehazeFormer] 用本文的代码和数据集跑不出本论文中所说的baseline (Issue #12)




 
batch size变小的话，实验结果变低是比较正常的。
 请问学习率有根据batch size改变进行更改么。

**Comment by IDKiro** [comment]
如果batch size是原来的1/4的话，学习率也需要改成1/4。
你可以看一下：https://www.zhihu.com/question/64134994。
相应的论文我就不贴了。

实验设置因为硬件条件限制对不齐是比较正常的，好的硬件确实容易得到好的结果。
但是做实验除了摘抄之前论文的结果，也可以按照自己做的结果贴。

其实indoor的实验每篇论文都不一样，如果你追求更高的PSNR，你可以尝试加大epoch，因为baselines和dehazeformer其实都没有完全收敛。

**Comment by Lizi271** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月16日(周四) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDKiro/DehazeFormer] 用本文的代码和数据集跑不出本论文中所说的baseline (Issue #12)




 
如果batch size是原来的1/4的话，学习率也需要改成1/4。
 你可以看一下：https://www.zhihu.com/question/64134994。
 相应的论文我就不贴了。
 
实验设置因为硬件条件限制对不齐是比较正常的，好的硬件确实容易得到好的结果。
 但是做实验除了摘抄之前论文的结果，也可以按照自己做的结果贴。
 
其实indoor的实验每篇论文都不一样，如果你追求更高的PSNR，你可以尝试加大epoch，因为baselines和dehazeformer其实都没有完全收敛。

**Comment by IDKiro** [comment]
我先把issue关了，之后如果有问题可以发邮件问我，邮件我基本每天都看的。

**Comment by Lizi271** [comment]
我跑了dehazeformer-t,数据集(ITS),按照您原论文中batchsize=32，lr=4e-4,得到的结果是PSNR=34.89，SSIM=0.9888。

---Original---
From: ***@***.***&gt;
Date: Thu, Jun 16, 2022 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results inthe paper (Issue #12)




 
我先把issue关了，之后如果有问题可以发邮件问我，邮件我基本每天都看的。

**Comment by IDKiro** [comment]
不太清楚到底是什么原因导致，有可能：
1. 环境不一致，比如包不一致，之前我碰到过conda和pip都安装了多个opencv的情况，结果调用比较混乱
2. 训练的随机性导致，但是你两个实验都是低0.25dB左右，感觉可能性不大
3. 开源代码和实验代码不一致导致，但是DehazeFormer-T在indoor上的实验的35.15是最后做消融的时候跑的，那时候代码应该和开源的没大差别（主要是删了一些无用代码然后整理了下），这部分实验都保存了log，这里贴上DehazeFormer-T的log
[dehazeformer-t.zip](https://github.com/IDKiro/DehazeFormer/files/8932924/dehazeformer-t.zip)，你对照一下是什么时候产生差异的

**Comment by IDKiro** [comment]
不好意思，我刚才看了一下，好像你之前S的实验设置也是对齐的？
我把它和现在在跑的实验的实验设置看串了。

**Comment by Lizi271** [comment]
之前S的实验设置是batchsize=16,lr=2e-4



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 18, 2022 13:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results inthe paper (Issue #12)




 
不好意思，我刚才看了一下，好像你之前S的实验设置也是对齐的？
 我把它和现在在跑的实验的实验设置看串了。

**Comment by IDKiro** [comment]
> 之前S的实验设置是batchsize=16,lr=2e-4

这就是原本的实验设置，因为最近在跑一个新模型，batch size设成了64，所以搞混了以为你的batch size改小了。

这份代码的绝大部分实验是在4卡2080Ti上跑的，indoor实验上并没有观察到±0.1dB以上的结果随机性（RESIDE-6K上倒是有）。
如果你确定没有改代码，实验设置对齐，并且排除运行环境差异的可能，那具体原因我也没办法确定。最近手头有DehazeFormer的改进版以及一个新的模型要跑，暂时没计划腾出计算资源和时间帮你细致排查问题。

**Comment by Lizi271** [comment]
我能确定没有改代码，实验设置对齐，但是我不能排除运行环境差异的可能，我是在1卡3080Ti上跑的，我不知道是否是这个原因造成的

---Original---
From: ***@***.***&gt;
Date: Sat, Jun 18, 2022 14:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results in the paper (Issue #12)




  
之前S的实验设置是batchsize=16,lr=2e-4
  
这就是原本的实验设置，因为最近在跑一个新模型，batch size设成了64，所以搞混了以为你的batch size改小了。
 
这份代码的绝大部分实验是在4卡2080Ti上跑的，indoor实验上并没有观察到±0.1dB以上的结果随机性（RESIDE-6K上倒是有）。
 如果你确定没有改代码，实验设置对齐，并且排除运行环境差异的可能，那具体原因我也没办法确定。最近手头有DehazeFormer的改进版以及一个新的模型要跑，暂时没计划腾出计算资源和时间帮你细致排查问题。

**Comment by IDKiro** [comment]
不排除这个影响，虽然LayerNorm（以及本文的改版）没有BatchNorm那样对batch size那么敏感。如果确保实验设置和运行环境（pytorch、cuda以及opencv等的版本、安装方式）一致，那么可能原因是设备差异导致的奇怪问题了，这确实不好排除。

为了方便消融实验（防止改了模块之后的网络爆显存），本文的小模型并没有跑满总共44GB的显存，但是也应该要24GB以上才能对齐实验设置才对，即使是12GB显存的新款3080Ti应该也是不够的。我对此还是挺疑惑的，难道是PyTorch（或者其他包）在混合精度训练时会根据显存大小自动调整训练精度？

如果要写论文，FFANet之后大部分在SOTS indoor和outdoor上的结果一般都是摘抄先前工作，所以确实会对你产生不利。当然你也可以重新跑所有baseline，然后在论文的实验设置部分注明。如果你先按照现有实验条件继续实验，只要实验设置对齐，总能在试一些idea后找到改进点的，到时候可以尝试租台4卡服务器跑跑看。

**Comment by Lizi271** [comment]
好的，我用的是3090Ti跑的，谢谢您耐心的解答!



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 18, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results in the paper (Issue #12)




 
不排除这个影响，虽然LayerNorm（以及本文的改版）没有BatchNorm那样对batch size那么敏感。如果确保实验设置和运行环境（pytorch、cuda以及opencv等的版本、安装方式）一致，那么可能原因是设备差异导致的奇怪问题了，这确实不好排除。
 
为了方便消融实验（防止改了模块之后的网络爆显存），本文的小模型并没有跑满总共44GB的显存，但是也应该要24GB以上才能对齐实验设置才对，即使是12GB显存的新款3080Ti应该也是不够的。我对此还是挺疑惑的，难道是PyTorch（或者其他包）在混合精度训练时会根据显存大小自动调整训练精度？
 
如果要写论文，FFANet之后大部分在SOTS indoor和outdoor上的结果一般都是摘抄先前工作，所以确实会对你产生不利。当然你也可以重新跑所有baseline，然后在论文的实验设置部分注明。如果你先按照现有实验条件继续实验，只要实验设置对齐，总能在试一些idea后找到改进点的，到时候可以尝试租台4卡服务器跑跑看。

**Comment by IDKiro** [comment]
很遗憾，似乎并没有帮到忙。
搞定手头的事情后我会去解决下这问题，毕竟训练结果如果受到运行环境的影响也不是什么好事情。

**Comment by Lizi271** [comment]
没关系的，您先忙完手里的事，到时候如果您解决了这个问题，我们再交流一下，谢谢!



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 18, 2022 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results in the paper (Issue #12)




 
很遗憾，似乎并没有帮到忙。
 搞定手头的事情后我会去解决下这问题，毕竟训练结果如果受到运行环境的影响也不是什么好事情。

**Comment by binwang777** [comment]
作者应该训练的时候保存一下随机种子吧，如果有了随机种子就不会出现当下问题了。刷分有波动蛮正常的。

**Comment by IDKiro** [comment]
> 作者应该训练的时候保存一下随机种子吧，如果有了随机种子就不会出现当下问题了。刷分有波动蛮正常的。

确实是我的问题，平时从来不固定随机种子，因为觉得固定随机种子比较trick。
我上次刷点还是图像去噪，图像去噪提点困难但是结果是比较稳定的，性能波动一般不超过0.05dB，思维惯性了。

**Comment by Lizi271** [comment]
好的谢谢





---Original---
From: ***@***.***&gt;
Date: Thu, Jun 16, 2022 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] My results do not agree with the results inthe paper (Issue #12)




 
我先把issue关了，之后如果有问题可以发邮件问我，邮件我基本每天都看的。

**Comment by Zyyy0828** [comment]
这个可以与yolo算法结合使用吗？

**Comment by Lizi271** [comment]
没试过












李子
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDKiro/DehazeFormer] 实验结果复现 (Issue #12)




 
这个可以与yolo算法结合使用吗？
