### ISSUE TITLE
复现实验结果未能达到论文中所列的精度

### ISSUE THREAD

**Issue by Magic-Koala** [IDKiro/DehazeFormer#13]
我在使用dehazeformer-t模型按作者设置的参数在reside6k数据集上进行实验，best_psnr只能达到29.88dB，经过测试集测试只有30.09dB而论文中报告的结果是30.36dB。我想询问作者是什么原因导致了精度的下降，这样的下降是合理的吗？或者是什么原因导致的呢？

**Comment by IDKiro** [comment]
reside6k上的实验确实要比reside-indoor不稳定很多，这个幅度不排除是噪声。
我前期的消融实验是在reside6k上面做的，这里有一些做了两次的消融实验（这些消融和论文中写的不是一个东西），有部分数据确实两次实验数据差的比较大，所以后来就在reside-indoor上做的。
![image](https://user-images.githubusercontent.com/24263261/177724257-cbd27b33-fc0e-4091-be59-85933bf40181.png)
至于其他的原因，我不太确定，你可以参考 #12 ，里面也有一些讨论。
这里也给你我的log，[dehazeformer-t.zip](https://github.com/IDKiro/DehazeFormer/files/9061594/dehazeformer-t.zip)，可以对比一下。
我论文中的绝大部分实验就只跑了一次，关于实验随机误差的实验我打算等一审意见出了再说了。
