### ISSUE TITLE
关于PFDN的问题

### ISSUE THREAD

**Issue by a996095396** [IDKiro/DehazeFormer#14]
想问下作者PFDN在RESIDE-6k 和RS-Haze上的结果是怎么出来的，最近看到这篇文章，想做一些相关的实验，但是没有找到PFDN的源码。请问作者是否有PFDN的源码。谢谢

**Comment by IDKiro** [comment]
[pfdn.zip](https://github.com/IDKiro/DehazeFormer/files/9276038/pfdn.zip)
自己实现的，最后的结构很简单，性能也一般，不排除实现时遗漏了什么细节。
