### ISSUE TITLE
有朋友能告诉我吗，最少需要啥配置的GPU能训练indoor模型？

### ISSUE THREAD

**Issue by AmeryXiong** [IDKiro/DehazeFormer#15]
我用两张3090（48G显存）怎么训练不了indoor这个数据集？？

**Comment by IDKiro** [comment]
3090*2可以训练，这篇论文的实验最多只用了2080Ti * 4。
你可以排查下自己CPU的线程数，GPU上是否有其他程序，数据是否放在SSD上。

**Comment by IDKiro** [comment]
暂时关闭这个issue
