### ISSUE TITLE
How to calculate PSNR and SSIM? Python or MATLAB?

### ISSUE THREAD

**Issue by morgen-star** [IDKiro/DehazeFormer#18]
Dear author,

Thanks for your work.  How to evaluate PSNR and SSIM?

I find that the author of RESIDE provides the matlab version for the performance calculation on the dataset website.

But you use the python version.  So, which one is correct?

Thanks for your reply in advance.

**Comment by IDKiro** [comment]
The precision supported by MATLAB is higher than that of python, but this does not lead to differences in the results. 
PSNR is very simple, while SSIM includes the setting of parameters such as the window size and variance of the Gaussian kernel, but the settings used in this repository are the same as the original MATLAB code.
If you are looking for a more rigorous comparison, you can use MATLAB code, although this can make the evaluation process tedious.
