### ISSUE TITLE
OTS dataset

### ISSUE THREAD

**Issue by hdcxqrc** [IDKiro/DehazeFormer#19]
请问OTS数据集313950 包含了测试集里面（500）的图片了啊

**Comment by IDKiro** [comment]
#9 ，这问题也算是历史遗留问题了，这里先把issue关了

**Comment by IDKiro** [comment]
因为你连续开了两个issue，这里删掉了后一个，并回答另外一个issue的问题。
论文尚在投稿中，并未被录用。
你自己的baseline的实验结果的差异可能是因为实验设置的差异导致，我的实验设置跟随之前FFANet等工作扩展。如果是要写论文，可以报告自己的实验设置和相应的结果，也可以跟随之前的实验设置然后复制已有论文的结果。

**Comment by hdcxqrc** [comment]
请问可以上传对比实验的可视化结果图么，如FFA在6k数据集下的结果图
