### ISSUE TITLE
Hi, I want know where RESIDE-6k come from? 

### ISSUE THREAD

**Issue by AmeryXiong** [IDKiro/DehazeFormer#21]
因为您论文里面说 RESIDE-6K 的配置和FFA-net一样，但是我并没有发现FFA-Net使用了 RESIDE-6k?

![image](https://user-images.githubusercontent.com/102467128/221075046-21356a0e-9b07-4dc0-98ff-d7b83703b642.png)
![image](https://user-images.githubusercontent.com/102467128/221075158-0c6f4bc2-91f8-4e9d-bd80-da578658bc36.png)

**Comment by IDKiro** [comment]
不好意思，引用错了论文，应该是 "Domain Adaptation for Image Dehazing"，真的非常感谢你的提醒！

**Comment by IDKiro** [comment]
这是你第二次指出细节上的错误了，向你表示真心的感谢
