### ISSUE TITLE
您好，谢谢您的工作，我注意到您的论文中增加了新的数据集Dense-haze和NH-haze结果。

### ISSUE THREAD

**Issue by AmeryXiong** [IDKiro/DehazeFormer#22]
1.但是在论文中并没有指出这两个数据集中哪些图片是训练集和哪些图片是测试集，这在很多论文中都没被指出，请问您能提供相关的信息吗？
2.请问能更新这两个数据集相关的配置文件和训练代码吗？
3.请问TIP论文中这两个数据集的FFA-Net,DehazeNet,AOD-Net出来的图片是怎么哪里来的，请问这些模型是使用这两个数据集重新训练的吗，请问能提供训练过程和更新预训练模型吗？

谢谢😊

**Comment by IDKiro** [comment]
同学你好，首先回复你的问题：
1. 数据集设置和AECR-Net是对齐的，具体实验设置来自论文“Trident Dehazing Network” （TDN），是个比较老的实验设置
2. 这部分是在two-branch的代码上改的，但是整合进这个repo有点麻烦（主要是多了个GAN），应该不会去花时间重构整合代码
3. baseline的这几张图片是AECR-Net的arxiv版本论文源码中提供的，没有对baseline进行重新训练

因为我个人不喜欢那几个小数据集，所以这些实验都是被审稿人要求了之后才加的。整体上做实验的时候就是图方便只训练了dehazeformer-s，其他结果用的AECR-Net贴的结果，所以你会发现baseline的结果不管是定性还是定量都是一样的。

可能因为数据集太小了，模型在训练时很依赖运气，有时候NH-Haze的PSNR会很快到20dB以上，有时候则卡在18.5不动（甚至直接loss跑飞了），导致我最后都不知道加的损失项和加载预训练模型是不是真的有用（更大的训练patch size应该是有用的）。如果你发现训练出的模型跑不过baseline，我建议多跑几次，很可能只是运气不好（）。

**Comment by AmeryXiong** [comment]
十分感谢！

**Comment by AmeryXiong** [comment]
我也是因为审稿人要求需要添加real-datasets，但是在哪都找不到real-datasets的训练细节，十分感谢，祝您博士早日毕业！
