### ISSUE TITLE
About the mixed real world dataset

### ISSUE THREAD

**Issue by 666zz666** [IDKiro/DehazeFormer#24]
Thanks for your amazing work！
I would like to train a smaller model on this dataset.
Would you mind sharing the composition of the mixed dataset and its training hyperparameters?

**Comment by IDKiro** [comment]
I'm busy these days, and I may upload it next week.

**Comment by 666zz666** [comment]
Thanks for your response！

**Comment by IDKiro** [comment]
For convenience, I uploaded the dataset to baidu pan:
https://pan.baidu.com/s/1oXmYvrwejVsazmaKaIyhjg?pwd=wu5n
