### ISSUE TITLE
RSHaze

### ISSUE THREAD

**Issue by wjpoet** [IDKiro/DehazeFormer#25]
Hello, thank you for a job well done. What tools did you use to synthesize the RSHaze dataset? Can you share? thank you

**Comment by IDKiro** [comment]
The tools used to read the remote-sensing images are described in the paper, while the synthesis pipeline is implemented using Python. Although I contributed the solution for the synthesis pipeline, the code was implemented by another author, so this part was planned to be made public by another author. Unfortunately, he has graduated a few months ago and does not want to spend effort on organizing this part of the code.

Translated with www.DeepL.com/Translator (free version)

**Comment by wjpoet** [comment]
It's a shame. Thank you for your reply.



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 30, 2023 23:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] RSHaze (Issue #25)




 
The tools used to read the remote-sensing images are described in the paper, while the synthesis pipeline is implemented using Python. Although I contributed the solution for the synthesis pipeline, the code was implemented by another author, so this part was planned to be made public by another author. Unfortunately, he has graduated a few months ago and does not want to spend effort on organizing this part of the code.
 
Translated with www.DeepL.com/Translator (free version)

**Comment by IDKiro** [comment]
I'm sorry I didn't help you, maybe when he's free I can ask him for a copy of the unorganized code and I'll let you know then.

**Comment by wjpoet** [comment]
That couldn't be better. Thank you. I'm waiting for your good news.



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 1, 2023 11:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] RSHaze (Issue #25)




 
I'm sorry I didn't help you, maybe when he's free I can ask him for a copy of the unorganized code and I'll let you know then.

**Comment by zhuqinghe** [comment]
> That couldn't be better. Thank you. I'm waiting for your good news.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 1, 2023 11:51 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [IDKiro/DehazeFormer] RSHaze (Issue #25) I'm sorry I didn't help you, maybe when he's free I can ask him for a copy of the unorganized code and I'll let you know then. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hello, i'm the "another author" mentioned above. i'm sry for the late reply. May this part of code(https://github.com/zhuqinghe/RS-Haze) will help you. You can create an issue in that repository if you have further problem about RS-Haze dataset. I'm trying to organize the work about RS-Haze dataset and make it public on weekends (this may take a while because i haven‘t done related work for a long time ... ).

**Comment by wjpoet** [comment]
OK. Thank you for your help.


---Original---
From: ***@***.***&gt;
Date: Sun, Jul 2, 2023 16:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDKiro/DehazeFormer] RSHaze (Issue #25)




  
That couldn't be better. Thank you. I'm waiting for your good news.
 …
 ---Original--- From: @.&gt; Date: Sat, Jul 1, 2023 11:51 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [IDKiro/DehazeFormer] RSHaze (Issue #25) I'm sorry I didn't help you, maybe when he's free I can ask him for a copy of the unorganized code and I'll let you know then. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Hello, i'm the "another author" mentioned above. i'm sry for the late reply. May this part of code(https://github.com/zhuqinghe/RS-Haze) will help you. You can create an issue in that repository if you have further problem about RS-Haze dataset. I'm trying to organize the work about RS-Haze dataset and make it public on weekends (this may take a while because i haven‘t done related work for a long time ... ).
