### ISSUE TITLE
关于训练和测试图像的处理问题

### ISSUE THREAD

**Issue by luoxuanxx** [IDKiro/DehazeFormer#31]
非常棒的一项工作，我能从之前的issues中得知，您在训练中把图像裁切成了多个256*256的补丁并进行数据增强，而在测试中，没有进行剪切，但我在 loader.py 中的第 79~83 行，仍然发现您使用了align函数进行了裁切，这好像跟您之前issues中回答的不同。
并且，我想知道如果测试时也要裁切的话，最终结果是怎么合并到一起的，相关的代码在哪个位置呢。

**Comment by IDKiro** [comment]
那个是validation，和test不是同一个

**Comment by luoxuanxx** [comment]
非常感谢，我明白模型是怎样操作的了
