### ISSUE TITLE
What's the difference among the four pre-trained models: dehazeformer-b, dehazeformer-m, dehazeformer-t and dehazeformer-s?

### ISSUE THREAD

**Issue by Inglam** [IDKiro/DehazeFormer#32]
What's the difference among the four published outdoor pre-trained models: dehazeformer-b, dehazeformer-m, dehazeformer-t and dehazeformer-s? Thanks! @IDKiro

**Comment by IDKiro** [comment]
model size

**Comment by Inglam** [comment]
Thanks! What is your email address? My team is interested in a potential cooperation with you/your team. Look forward to your response!
