### ISSUE TITLE
An error occurred running train.py ，How can this be resolved？

### ISSUE THREAD

**Issue by 98-xiaowu** [IDKiro/DehazeFormer#6]
The following error occurred running the train.py file：

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

After adding the code "os.environ['CUDA_LAUNCH_BLOCKING'] = '1'"，an error is still reported：
RuntimeError: CUDA error: out of memory

**Comment by IDKiro** [comment]
40G GPU memory is required to run the train code (4 * RTX2080Ti or 8 * RTX3080 are used in our experiment)

You can lower the batch size of the config file and reduce the learning rate according to your GPU.

Take `configs/indoor/dehazeformer-t.json` for example:

```
{
    "batch_size": 32,
    "patch_size": 256,
    "valid_mode": "test",
    "edge_decay": 0,
    "only_h_flip": false,
    "optimizer": "adamw",
    "lr": 4e-4,
    "epochs":300,
    "eval_freq": 1
}
```

to 

```
{
    "batch_size": 8,
    "patch_size": 256,
    "valid_mode": "test",
    "edge_decay": 0,
    "only_h_flip": false,
    "optimizer": "adamw",
    "lr": 1e-4,
    "epochs":300,
    "eval_freq": 1
}
```

**Comment by IDKiro** [comment]
这算是比较常见的问题了，出现的时候可以先在[stackoverflow](https://stackoverflow.com/)搜一下

**Comment by 98-xiaowu** [comment]
> 40G GPU memory is required to run the train code

I modified it according to your method, but it still went wrong.Is it because I don't have enough GPU memory?
![image](https://user-images.githubusercontent.com/73646738/166625432-83546be2-eef7-4d59-85c1-d1783db22d59.png)

**Comment by IDKiro** [comment]
Your environment (CUDA PyTorch ... )?

Such an unbalanced GPU allocation does not look like a common mistake

**Comment by 98-xiaowu** [comment]
> Your environment (CUDA PyTorch ... )?
> 
> Such an unbalanced GPU allocation does not look like a common mistake.
> 
> Can you show the complete nvidia-smi information?

![image](https://user-images.githubusercontent.com/73646738/166625936-366c0538-7c1a-431b-8b50-6f24b5ca31b0.png)
![image](https://user-images.githubusercontent.com/73646738/166625949-8a6f2b3d-18af-452a-9d79-f7fdb7ffb987.png)

**Comment by 98-xiaowu** [comment]
> Your environment (CUDA PyTorch ... )?
> 
> Such an unbalanced GPU allocation does not look like a common mistake.
> 
> Can you show the complete nvidia-smi information?

Does every GPUs need to have roughly the same amount of memory?

**Comment by IDKiro** [comment]
Did you run multiple experiments at the same time?
The process numbers of these python programs are not the same.
pytorch does not automatically allocate memory based on each GPU's remaining memory, it is generally allocated evenly

**Comment by IDKiro** [comment]
> > Your environment (CUDA PyTorch ... )?
> > Such an unbalanced GPU allocation does not look like a common mistake.
> > Can you show the complete nvidia-smi information?
> 
> Does every GPUs need to have roughly the same amount of memory?

Yes

**Comment by 98-xiaowu** [comment]
> > > Your environment (CUDA PyTorch ... )?
> > > Such an unbalanced GPU allocation does not look like a common mistake.
> > > Can you show the complete nvidia-smi information?
> > 
> > 
> > Does every GPUs need to have roughly the same amount of memory?
> 
> Yes

thanks,The program is up and running

> > > Your environment (CUDA PyTorch ... )?
> > > Such an unbalanced GPU allocation does not look like a common mistake.
> > > Can you show the complete nvidia-smi information?
> > 
> > 
> > Does every GPUs need to have roughly the same amount of memory?
> 
> Yes

Thank you,the program is up and running,But it's slower. It takes long time to train a epoch.Is this normal?

**Comment by IDKiro** [comment]
DehazeFormer-T for indoor may takes 12 hours to train.

DehazeFormer-L needs 1 week.

**Comment by 98-xiaowu** [comment]
> DehazeFormer-T for indoor may takes 12 hours to train.
> 
> DehazeFormer-L needs 1 week.

OK，Thank you for your response.

**Comment by IDKiro** [comment]
Glad to help you!
