### ISSUE TITLE
test datasets

### ISSUE THREAD

**Issue by sz19980502** [IDKiro/DehazeFormer#8]
Good job! Does the experiment in your paper need to resize the test image to the same size as the training image?

**Comment by IDKiro** [comment]
No, you can feed images of any resolution during testing.
Also, we don't resize the images during training, just crop them to 256x256 patches.

**Comment by IDKiro** [comment]
Reopen it if necessary.

**Comment by Algolzw** [comment]
Hi, do you crop all images to 256x256 in both training and testing (as shown in the [PairLoader](https://github.com/IDKiro/DehazeFormer/blob/e76a0d7aff5a736457d6b6555516145094a38997/datasets/loader.py#L54))?

**Comment by IDKiro** [comment]
> Hi, do you crop all images to 256x256 in both training and testing (as shown in the [PairLoader](https://github.com/IDKiro/DehazeFormer/blob/e76a0d7aff5a736457d6b6555516145094a38997/datasets/loader.py#L54))?

No, see lines 82~83 in loader.py
